### ISSUE TITLE
Change midi BPM

### ISSUE THREAD

**Issue by FabioZumbi12** [kewlniss/CSharpSynthForUnity#3]
Hi,
Is not exaclty an issue but i didnt found any forum where i can post questions about this. How to change the midi bpm using this library?

**Comment by HowdyChad** [comment]
I've not had the requirement, so I've not dug into the code myself. I simply ported it from the project at codeplex. 

I just put this out here to hopefully help some folks, but don't have any time to devote to it, since I didn't actually create this and am not super familiar with the internals of the code.

Now, with that being said, I see that in the MidiFile.cs there is BPM of 120 and in MidiSequencer the BeatsPerMinute is set to 120. You may want to play with those numbers...

https://github.com/kewlniss/CSharpSynthForUnity/search?utf8=%E2%9C%93&q=bpm&type=

**Comment by FabioZumbi12** [comment]
I apprecieate your work. Its really working well on Unity.

And this problem seems is present on oficial code from codeplex, i found a topic about tempo and bpm dont change when  setting the BPM from Midi. here is the topic: https://csharpsynthproject.codeplex.com/discussions/660168

I just was needing to sync one music with a midi, but now instead to sync using bpm, i using the samples time to make the sync.

Thank you for your time.
